server:
  port: 8080

spring:
  main:
    web-application-type: servlet
  datasource:
    url: postgres://postgres:postgrespw@localhost:55001/organize
    username: pgadmin4@pgadmin.org
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PosterSQLDialect
        format_sql: true
      show_sql: true